#!/bin/bash
if [ $1 ]; then
   if [ -f $1 ]; then
       FILE_C=$1
       SIZE_P=`expr length $FILE_C`
       SIZE_SS=`expr $SIZE_P - 2`
       PKG_NM=`expr substr $FILE_C 1 $SIZE_SS`
       PODIR="po"
       PONMPOT=$PODIR/$PKG_NM.pot
       xgettext --package-name $PKG_NM --package-version 0.1 --default-domain $PKG_NM --output $PONMPOT --from-code=utf-8 --copyright-holder="h4773r" --msgid-bugs-address="heatseeker.persa@gmail.com" -s -k_ -L C $1
       sed  -i  's/CHARSET/UTF-8/g' $PONMPOT
       msginit -l en -o po/en.po -i $PONMPOT
       msginit -l es -o po/es.po -i $PONMPOT 
    else
       echo No existe el archivo
    fi
else
   echo use $0 archivo.c
fi          
   
